import pytest
from unittest.mock import MagicMock

from models.web_search_models import (
    SearchResult,
    WebSearchRequest,
)

from services.web_search.web_search_service import (
    WebSearchService,
)


class TestWebSearchService:

    def test_search_success(self):
        """
        Verify that a successful Tavily search and Gemini
        summarization returns a valid WebSearchResponse.
        """

        mock_client = MagicMock()

        mock_client.search.return_value = {
            "results": [
                {
                    "title": "FDA",
                    "url": "https://www.fda.gov",
                    "content": "FDA approves new treatment."
                }
            ]
        }

        mock_llm = MagicMock()

        mock_llm.generate_response.return_value = (
            "Summary generated by Gemini."
        )

        service = WebSearchService(
            client=mock_client,
            llm=mock_llm,
        )

        response = service.search(
            WebSearchRequest(
                question="Latest lung cancer treatment"
            )
        )

        assert response.answer == "Summary generated by Gemini."

        assert len(response.sources) == 1

        assert response.sources[0].title == "FDA"

        mock_client.search.assert_called_once()

        mock_llm.generate_response.assert_called_once()

    def test_search_with_no_results(self):
        """
        Verify that an empty Tavily response is handled correctly.
        """

        mock_client = MagicMock()

        mock_client.search.return_value = {
            "results": []
        }

        mock_llm = MagicMock()

        mock_llm.generate_response.return_value = (
            "No information available."
        )

        service = WebSearchService(
            client=mock_client,
            llm=mock_llm,
        )

        response = service.search(
            WebSearchRequest(
                question="Unknown disease"
            )
        )

        assert response.answer == "No information available."

        assert response.sources == []

    def test_search_tavily_failure(self):
        """
        Verify that Tavily exceptions are propagated.
        """

        mock_client = MagicMock()

        mock_client.search.side_effect = Exception(
            "Tavily API failed."
        )

        mock_llm = MagicMock()

        service = WebSearchService(
            client=mock_client,
            llm=mock_llm,
        )

        request = WebSearchRequest(
            question="Cancer"
        )

        with pytest.raises(RuntimeError, match="Medical web search failed."):
            service.search(request)

    def test_search_gemini_failure(self):
        """
        Verify that Gemini exceptions are propagated.
        """

        mock_client = MagicMock()

        mock_client.search.return_value = {
            "results": [
                {
                    "title": "FDA",
                    "url": "https://www.fda.gov",
                    "content": "FDA content"
                }
            ]
        }

        mock_llm = MagicMock()

        mock_llm.generate_response.side_effect = RuntimeError(
            "Gemini failed."
        )

        service = WebSearchService(
            client=mock_client,
            llm=mock_llm,
        )

        request = WebSearchRequest(
            question="Cancer"
        )

        with pytest.raises(RuntimeError):
            service.search(request)

    def test_convert_results(self):
        """
        Verify Tavily results are converted into SearchResult models.
        """

        service = WebSearchService(
            client=MagicMock(),
            llm=MagicMock(),
        )

        response = {
            "results": [
                {
                    "title": "WHO",
                    "url": "https://who.int",
                    "content": "WHO content"
                }
            ]
        }

        results = service._convert_results(response)

        assert len(results) == 1

        assert isinstance(results[0], SearchResult)

        assert results[0].title == "WHO"

        assert results[0].url == "https://who.int"

        assert results[0].content == "WHO content"

    def test_build_search_context(self):
        """
        Verify search context is built correctly for the LLM.
        """

        service = WebSearchService(
            client=MagicMock(),
            llm=MagicMock(),
        )

        context = service._build_search_context(
            [
                SearchResult(
                    title="FDA",
                    url="https://fda.gov",
                    content="Drug approved."
                )
            ]
        )

        assert "Title:" in context

        assert "FDA" in context

        assert "Content:" in context

        assert "Drug approved." in context