from models.sql_models import SQLGenerationResponse


class SQLParser:
    """
    Parses SQL generated by the LLM.
    """

    @classmethod
    def parse(
        cls,
        response: str,
    ) -> SQLGenerationResponse:
        """
        Parse SQL generated by the LLM.

        Args:
            response: Raw LLM response.

        Returns:
            Parsed SQL query.
        """

        sql_query = cls._extract_sql(response)

        cls._validate_sql(sql_query)

        return SQLGenerationResponse(
            sql_query=sql_query,
        )

    @classmethod
    def _extract_sql(
        cls,
        response: str,
    ) -> str:
        """
        Extract SQL from the raw LLM response.
        """

        if not response or not response.strip():
            raise ValueError("LLM returned an empty response.")

        sql_query = response.strip()

        if sql_query.startswith("```"):
            return cls._extract_markdown_sql(sql_query)

        return cls._extract_select_statement(sql_query)

    @staticmethod
    def _extract_markdown_sql(
        sql_query: str,
    ) -> str:
        """
        Extract SQL from a Markdown code block.
        """

        lines = sql_query.splitlines()

        if lines and lines[0].strip().lower() in {
            "```sql",
            "```",
        }:
            lines = lines[1:]

        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        return "\n".join(lines).strip()

    @staticmethod
    def _extract_select_statement(
        sql_query: str,
    ) -> str:
        """
        Extract the first SELECT statement from the response.
        """

        upper_query = sql_query.upper()

        select_index = upper_query.find("SELECT")

        if select_index == -1:
            raise ValueError(
                "No SELECT statement found in the LLM response."
            )

        sql_query = sql_query[select_index:]

        semicolon_index = sql_query.find(";")

        if semicolon_index != -1:
            sql_query = sql_query[: semicolon_index + 1]

        return sql_query.strip()

    @staticmethod
    def _validate_sql(
        sql_query: str,
    ) -> None:
        """
        Validate the extracted SQL.
        """

        if not sql_query:
            raise ValueError("No SQL query generated.")

        if not sql_query.lower().startswith("select"):
            raise ValueError(
                "Generated output is not a valid SELECT query."
            )